#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"

docker-compose -f "${SCRIPT_DIR}/docker-compose.yml" down --volumes


echo -e "\n        |||||   |||||   |||||  |||||   |||||     |||||   |||||         ||||    |||||   |        |       |   |    |   |"
echo "        |   |   |   |   |   |      |   |         |         |           |   |   |   |    |      | |     |    ||   |   |"
echo "        |||||   |||||   |   |      |   |||||     |         |           |   |   |   |     |    |   |   |     | |  |   |"
echo "        |       ||      |   |      |   |         |         |           |   |   |   |      |  |     | |      |  | |   "
echo -e "        |       |  |    |||||  |||||   |||||     |||||     |           ||||    |||||       |        |       |   ||   |\n"
